language: python

python:
  - '3.8'

services:
  - docker

script:
  - docker build -t docker.hallbregg.dynu.net/jwks-generator:latest .
  - docker run docker.hallbregg.dynu.net/jwks-generator:latest

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
  - docker push docker.hallbregg.dynu.net/jwks-generator:latest
